# -*- coding: utf-8 -*-
"""Copy of Copy of list operation

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16jX3ngSKxihGZCpAwv6KQKcBATq8Kg-m
"""

# Assignment 2
# write a program to print the largest and smallest number of the list
# Write a program to delete the alternative numbers in a list
# write a program to delete the odd number in a list and print the even numbers

a=[2,5,7,8,4,6,9]
a.sort()
print(a)
print("the smallest number:",a[:1])
print("the largest number:",a[-1:])



a=[1,2,3,4,5,6,7,8]
for i in range(len(a)):
  if (i%2)==0:
    print(a[i])

num=[2,3,4,5,6,7,8]
even=[]
odd=[]
for i in num:
  if i%2 ==0:
    even.append(i)
    
  else:
    odd.append(i)
    num.remove(i)
  
print(even)
print(num)