# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JKPTmxoa4HLarbNC-y3hQ8dO0v4umCrJ
"""

myfile=open("python.txt",'r+')
print(myfile.read())

myfile=open("python,txt",'w+')
myfile.write( "this is harshita")

myfile=open("python.txt",'a+')
myfile.write("\n this is machine learning")

#Create a simple calculator using python
#two inputs and operators should be selected by the user

a=int(input("enter the number"))
b=int(input("enter the number"))
choice=input('')
if choice =="+":
  print("addition of two numbers",a+b)
elif choice =="-":
  print("subtraction of two numbers",a-b) 
elif choice == "*":
  print("multiplication of two numbers",a*b)
elif choice =="/":
  print("division of two numders",a/b) 
else:
  ("invalid input")